__CONTAINER/comments-master/comments-master/config/routes.rb
Comments::Application.routes.draw do |map|
  resources :sites

  get "comments/embed.js" => "comments#embed"
  resources :comments
  get "home/index"

  root :to => "home#index"

end

__CONTAINER/comments-master/comments-master/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :site
  attr_protected :site_id, :spam
  before_save :check_for_spam

  validates :site_id, :name, :page_url, :body, :ip, :agent, :presence => true

  def site_key=(key)
    self.site = Site.find_by_token(key)
  end

  private
    def check_for_spam
      if site && site.url && site.akismet_key
        Net::HTTP.start("#{site.akismet_key}.rest.akismet.com") do |http|
          request = Net::HTTP::Post.new('/1.1/comment-check')

          data = { 'blog' => site.url, 'user_ip' => ip, 'user_agent' => agent,
            'comment_author' => name, 'comment_content' => body }
          data['referrer'] = referrer               if referrer
          data['comment_author_email'] = email      if email
          data['comment_author_url'] = author_url   if author_url

          request.set_form_data(data)
          result = http.request(request)
          if result.body != 'false'
            self.spam = true
          end
        end
      end
    end
end

__CONTAINER/comments-master/comments-master/app/models/site.rb
class Site < ActiveRecord::Base
  has_many :comments
  attr_protected :token
  before_create :generate_token

  class UrlValidator < ActiveModel::EachValidator
    def validate_each(record, attribute, value)
      begin
        uri = URI.parse(value)
      rescue URI::InvalidURIError
        record.errors[attribute] << "must be a valid URI"
      end
    end
  end

  class AkismetKeyValidator < ActiveModel::EachValidator
    def validate_each(record, attribute, value)
      if record.url && record.akismet_key
        Net::HTTP.start("rest.akismet.com") do |http|
          request = Net::HTTP::Post.new('/1.1/verify-key')
          request.set_form_data(:key => record.akismet_key, :blog => record.url)
          result = http.request(request)
          if result.body != 'valid'
            record.errors[attribute] << "is not valid"
          end
        end
      end
    end
  end

  with_options(:presence => true, :uniqueness => true) do |opts|
    opts.validates :name
    opts.validates :url, :url => true
  end
  validates :akismet_key, :akismet_key => true

  private
    def generate_token
      now = Time.now
      self.token = Digest::MD5.hexdigest(Digest::MD5.hexdigest("#{now.to_s}-#{now.usec}") + "omgcomments")
    end
end

__CONTAINER/comments-master/comments-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

__CONTAINER/comments-master/comments-master/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  # GET /comments
  # GET /comments.xml
  def index
    @site = Site.find_by_token(params[:site_key])
    @comments = @site ? @site.comments.where(:page_url => params[:page_url]).all : []

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @comments }
      format.json { render :json => @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.xml
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.xml
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.xml
  def create
    @comment = Comment.new(params[:comment])
    @comment.ip = request.remote_ip
    @comment.agent = request.user_agent
    @comment.referrer = request.referrer

    respond_to do |format|
      if @comment.save
        format.html { redirect_to(@comment, :notice => 'Comment was successfully created.') }
        format.xml  { render :xml => @comment, :status => :created, :location => @comment }
        format.json { render :json => @comment, :status => :created, :location => @comment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
        format.json { render :json => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.xml
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(@comment, :notice => 'Comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.xml
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(comments_url) }
      format.xml  { head :ok }
    end
  end

  def embed
    render :template => "comments/embed.js.erb"
  end
end

__CONTAINER/comments-master/comments-master/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

__CONTAINER/comments-master/comments-master/app/controllers/sites_controller.rb
class SitesController < ApplicationController
  # GET /sites
  # GET /sites.xml
  def index
    @sites = Site.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sites }
    end
  end

  # GET /sites/1
  # GET /sites/1.xml
  def show
    @site = Site.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.xml
  def new
    @site = Site.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @site = Site.find(params[:id])
  end

  # POST /sites
  # POST /sites.xml
  def create
    @site = Site.new(params[:site])

    respond_to do |format|
      if @site.save
        format.html { redirect_to(@site, :notice => 'Site was successfully created.') }
        format.xml  { render :xml => @site, :status => :created, :location => @site }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.xml
  def update
    @site = Site.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to(@site, :notice => 'Site was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.xml
  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to(sites_url) }
      format.xml  { head :ok }
    end
  end
end

__CONTAINER/comments-master/comments-master/app/helpers/application_helper.rb
module ApplicationHelper
end

__CONTAINER/comments-master/comments-master/app/helpers/comments_helper.rb
module CommentsHelper
end

__CONTAINER/comments-master/comments-master/app/helpers/home_helper.rb
module HomeHelper
end

__CONTAINER/comments-master/comments-master/app/helpers/sites_helper.rb
module SitesHelper
end

__CONTAINER/comments-master/comments-master/app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <%= f.error_messages %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

__CONTAINER/comments-master/comments-master/app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

__CONTAINER/comments-master/comments-master/app/views/comments/embed.js.erb
(function($) {
  $.fn.comments = function(options) {
    return this.each(function(i) {
      var opts = $.extend({}, options, { stamp: new Date().getTime().toString() });
      new $.comments(this, opts);
    });
  };

  $.comments = function(el, options) {
    this.target = $(el);
    this.options = options;
    this.addComments();
    this.addForm();
  }

  $.extend($.comments.prototype, {
    target: null, options: null, form: null, name: null, body: null,
    list: null, header: null, count: 0,

    addComments: function() {
      $.ajax({
        url: "<%= comments_url(:format => 'json') %>",
        context: this,
        data: {
          site_key: this.options.siteKey,
          page_url: document.location.href
        },
        success: function(data) {
          container = $('<div></div>');
          this.header = $('<h3>Comments</h3>').appendTo(container);
          this.list = $('<ul></ul>').attr({
            id: 'comments_list_'+this.options.stamp,
            'class': 'comments_list'
          }).appendTo(container);

          var self = this;
          $.each(data, function() { self.appendComment(this); });
          this.updateHeader();

          this.target.prepend(container);
        }
      });
    },

    updateHeader: function() {
      this.header.html(this.count + ' Comment' + (this.count == 1 ? '' : 's'));
    },

    appendComment: function(comment) {
      item = $('<li></li>').attr({
        id: 'comment_'+comment.id, 'class': 'comment'
      });
      $('<div></div>').addClass('comment_name').html(comment.name).appendTo(item);
      $('<div></div>').addClass('comment_date').html(comment.created_at).appendTo(item);
      $('<div></div>').addClass('comment_body').html(comment.body).appendTo(item);
      this.list.append(item);
      this.count += 1;
    },

    addForm: function() {
      this.form = $('<form></form>').attr({
        action: "<%= comments_url(:format => 'json') %>",
        method: "post", id: 'comments_form_'+this.options.stamp,
        'class': 'comments_form'
      });

      // this.appendHiddenElement('authenticity_token', "<%= form_authenticity_token %>");
      this.appendHiddenElement('comment[page_url]', document.location.href);
      this.appendHiddenElement('comment[site_key]', this.options.siteKey);

      this.appendFormElement('text', 'name', 'Name:');
      this.appendFormElement('text', 'email', 'E-mail:');
      this.appendFormElement('text', 'author_url', 'URL:');
      this.appendFormElement('textarea', 'body', 'Type your comment here.');
      this.appendFormElement('submit', 'submit', 'Submit');

      this.body.focusin(function() {
        if ($(this).val() == "Type your comment here.") { $(this).val(""); }
      }).focusout(function() {
        if ($(this).val() == "") { $(this).val("Type your comment here."); }
      });
      this.form.bind('submit', this, function(e) {
        var self = $(this);
        if (e.data.body.val() == "Type your comment here.") { e.data.body.val(""); }
        $.ajax({
          url: self.attr('action'),
          data: self.serialize(),
          type: 'POST',
          context: e.data,
          success: function(data) {
            this.appendComment(data);
            this.updateHeader();
            this.form[0].reset();
            this.form.find('*').removeClass('error');
          },
          error: function(xhr) {
            data = $.parseJSON(xhr.responseText);
            var self = this;
            $.each(data, function(key, value) {
              self.form.find('.new_comment_'+key).addClass('error');
            });
          }
        });
        return false;
      });

      this.target.append(this.form);
    },

    appendHiddenElement: function(name, value) {
      $("<input />").attr({
        name: name, type: 'hidden', value: value
      }).appendTo(this.form);
    },

    appendFormElement: function(type, name, label) {
      var id = 'new_comment_' + name + '_' + this.options.stamp;
      var klass = 'new_comment_' + name;
      var div = $('<div></div>').addClass('new_comment_'+name);
      var obj = $(type == 'textarea' ? '<textarea></textarea>' : '<input type="'+type+'"></input>');
      obj.attr({ id: id, 'class': klass });

      if (type == 'submit' || type == 'textarea' || type == 'hidden')
        obj.val(label);
      else if (label != null)
        $('<label>'+label+'</label>').attr({'for': id, 'class': klass}).prependTo(div);

      if (type != 'submit')
        obj.attr('name', 'comment['+name+']');

      this.form.append(div.append(obj));
      this[name] = obj;
    }
  });
})(jQuery);

__CONTAINER/comments-master/comments-master/app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Body</th>
    <th>Page Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.name %></td>
    <td><%= comment.body %></td>
    <td><%= comment.page_url %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

__CONTAINER/comments-master/comments-master/app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

__CONTAINER/comments-master/comments-master/app/views/comments/show.html.erb
<p>
  <b>Name:</b>
  <%= @comment.name %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>Page Url:</b>
  <%= @comment.page_url %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

__CONTAINER/comments-master/comments-master/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

__CONTAINER/comments-master/comments-master/app/views/layouts/comments.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Comments: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

__CONTAINER/comments-master/comments-master/app/views/layouts/sites.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sites: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

__CONTAINER/comments-master/comments-master/app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <%= f.error_messages %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :akismet_key %><br />
    <%= f.text_field :akismet_key %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

__CONTAINER/comments-master/comments-master/app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

__CONTAINER/comments-master/comments-master/app/views/sites/index.html.erb
<h1>Listing sites</h1>

<table>
  <tr>
    <th>Name</th>
    <th>URL</th>
    <th>Token</th>
    <th>Akismet Key</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sites.each do |site| %>
  <tr>
    <td><%= site.name %></td>
    <td><%= site.url %></td>
    <td><%= site.token %></td>
    <td><%= site.akismet_key %></td>
    <td><%= link_to 'Show', site %></td>
    <td><%= link_to 'Edit', edit_site_path(site) %></td>
    <td><%= link_to 'Destroy', site, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Site', new_site_path %>

__CONTAINER/comments-master/comments-master/app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

__CONTAINER/comments-master/comments-master/app/views/sites/show.html.erb
<p>
  <b>Name:</b>
  <%= @site.name %>
</p>

<p>
  <b>Token:</b>
  <%= @site.token %>
</p>


<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>